### PR TITLE
Pull request for tickets #1 and #2

### PR DESCRIPTION
**Pull request by vasyl-krupa**
This pull request contains changes that make it possible to update the article element and breadcrumbs by clicking on TOC topic link. 
If the topic is opened as a file in the browser - the page will be updated.

### CODE REVIEW

**Review by ibarinova — CHANGES_REQUESTED** [review]
Please add comments in the DITA-OT original code and provide info what was added/changed/removed

**Review by ibarinova — APPROVED** [review]
Looks good for me.

**Comment by yuliia-biletska** [comment]
looks good

**Review by yuliia-biletska — APPROVED** [review]
looks good

**Pull request merged**
