### PR TITLE
Xrwh 110 move fig callouts into 2 columns

### PR DESCRIPTION
**Pull request by ibarinova**

### CODE REVIEW

**Review by yuliia-biletska — APPROVED** [review]
looks good

**Comment by vasyl-krupa** [comment]
Should we support sl lists? Because input content contains this type of list and output doesn't change. Otherwise looks good.

**Comment by ibarinova** [comment]
> Should we support sl lists? Because input content contains this type of list and output doesn't change. Otherwise looks good.

@vasyl-krupa Callouts - is something with numbers. Simple list is just a list with short items without any numbers or bullets (according to the DITA specification). So they don't look like callouts unless writer manually adds numbering at the beginning of simple list item.

We can add support for such list. In this case we shouldn't add numbering before LIs.

**Review by vasyl-krupa — APPROVED** [review]
Looks good

**Comment by vasyl-krupa** [comment]
OK, thanks

**Pull request merged**
