### PR TITLE
XRWH-2 Prev/next buttons implementation, small fix for breadcrumbs se…

### PR DESCRIPTION
**Pull request by vasyl-krupa**
…parator

### CODE REVIEW

**Comment by vasyl-krupa** [comment]
http://uarnet.intelliarts.com/vkrupa/vkrupa/index.html - latest output

**Review by yuliia-biletska — APPROVED** [review]
approved

**Comment by ibarinova** [comment]
@vasyl-krupa Was this implementation tested with topicrefs which have @chunk='to-content'?

**Review by ibarinova — APPROVED** [review]
Approved

**Pull request merged**
