### PR TITLE
Xrwh 139 compare current css with mockups and update formatting if required

### PR DESCRIPTION
**Pull request by yuliia-biletska**

### CODE REVIEW

**Comment by vasyl-krupa** [comment]
I merged dev into this branch and uploaded output here https://xslt-dev.intelliarts.com/vkrupa/index.html

**Review by ibarinova — APPROVED** [review]
Looks good

**Comment by vasyl-krupa** [comment]
I added fixes for the header title and search form layout. The latest output is here https://xslt-dev.intelliarts.com/vkrupa/GUID-6AC05AF1-5A72-4EF5-A134-BAA37948FAE8.html

@ibarinova could you please check?

**Review by ibarinova — APPROVED** [review]
Approved

**Pull request merged**
