### PR TITLE
XRWH-53 Add support for 'Hide/Show' button

### PR DESCRIPTION
**Pull request by vasyl-krupa**
latest output: http://uarnet.intelliarts.com/vkrupa/vkrupa/GUID-38559484-0C8F-4A64-9B9E-DDB9494267D1.html

### CODE REVIEW

**Review by yuliia-biletska — APPROVED** [review]
looks good for me

**Comment by vasyl-krupa** [comment]
http://uarnet.intelliarts.com/vkrupa/vkrupa/index.html - new code is uploaded

**Review by yuliia-biletska — APPROVED** [review]
very good

**Review by ibarinova — APPROVED** [review]
Approved

**Pull request merged**
