### PR TITLE
XRWH-45 TOC customization

### PR DESCRIPTION
**Pull request by vasyl-krupa**
Output: http://uarnet.intelliarts.com/vkrupa/vkrupa/index.html

### CODE REVIEW

**Review by yuliia-biletska — APPROVED** [review]
looks good

**Review by ibarinova — CHANGES_REQUESTED** [review]
1. Please increase left padding for .toc-container li.level* > .toc-element-row > a.
2. Also, all ancestors of active topic should have darker font color (like level1)
3. Use link to the image for arrows instead of using embedded images (url('data:image/svg+xml;utf8,). It it has any issues with try to find another fix.

**Comment by vasyl-krupa** [comment]
Output is updated, please check if it looks OK now

**Review by ibarinova — APPROVED** [review]
Approved

**Pull request merged**
